import Foundation

let catalogURL = URL(fileURLWithPath: CommandLine.arguments.dropFirst().first ?? "")
guard
    !catalogURL.path.isEmpty,
    let data = try? Data(contentsOf: catalogURL),
    var root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
    var strings = root["strings"] as? [String: Any]
else {
    fputs("Usage: review_localization_catalog.swift <Localizable.xcstrings>\n", stderr)
    exit(2)
}

let reviewed: [String: [String: String]] = [
    "%arg": [
        "zh-Hans": "%arg", "zh-Hant": "%arg", "en": "%arg", "ja": "%arg",
        "ko": "%arg", "es": "%arg", "fr": "%arg", "de": "%arg",
        "pt-BR": "%arg", "ru": "%arg", "ar": "%arg",
    ],
    "%arg / %arg": [
        "zh-Hans": "%arg / %arg", "zh-Hant": "%arg / %arg", "en": "%arg / %arg",
        "ja": "%arg / %arg", "ko": "%arg / %arg", "es": "%arg / %arg",
        "fr": "%arg / %arg", "de": "%arg / %arg", "pt-BR": "%arg / %arg",
        "ru": "%arg / %arg", "ar": "%arg / %arg",
    ],
    "%arg %arg": [
        "zh-Hans": "%arg %arg", "zh-Hant": "%arg %arg", "en": "%arg %arg",
        "ja": "%arg %arg", "ko": "%arg %arg", "es": "%arg %arg",
        "fr": "%arg %arg", "de": "%arg %arg", "pt-BR": "%arg %arg",
        "ru": "%arg %arg", "ar": "%arg %arg",
    ],
    "%arg ms": [
        "zh-Hans": "%arg 毫秒", "zh-Hant": "%arg 毫秒", "en": "%arg ms",
        "ja": "%arg ミリ秒", "ko": "%arg밀리초", "es": "%arg ms", "fr": "%arg ms",
        "de": "%arg ms", "pt-BR": "%arg ms", "ru": "%arg мс", "ar": "%arg مللي ثانية",
    ],
    "%arg，%arg": [
        "zh-Hans": "%arg，%arg", "zh-Hant": "%arg，%arg", "en": "%arg, %arg",
        "ja": "%arg、%arg", "ko": "%arg, %arg", "es": "%arg, %arg",
        "fr": "%arg, %arg", "de": "%arg, %arg", "pt-BR": "%arg, %arg",
        "ru": "%arg, %arg", "ar": "%arg، %arg",
    ],
    "Base URL": [
        "zh-Hans": "Base URL", "zh-Hant": "Base URL", "en": "Base URL", "ja": "Base URL",
        "ko": "Base URL", "es": "URL base", "fr": "URL de base", "de": "Basis-URL",
        "pt-BR": "URL base", "ru": "Базовый URL", "ar": "عنوان URL الأساسي",
    ],
    "http://127.0.0.1:%arg/v1": [
        "zh-Hans": "http://127.0.0.1:%arg/v1", "zh-Hant": "http://127.0.0.1:%arg/v1",
        "en": "http://127.0.0.1:%arg/v1", "ja": "http://127.0.0.1:%arg/v1",
        "ko": "http://127.0.0.1:%arg/v1", "es": "http://127.0.0.1:%arg/v1",
        "fr": "http://127.0.0.1:%arg/v1", "de": "http://127.0.0.1:%arg/v1",
        "pt-BR": "http://127.0.0.1:%arg/v1", "ru": "http://127.0.0.1:%arg/v1",
        "ar": "http://127.0.0.1:%arg/v1",
    ],
    "ModelHub": [
        "zh-Hans": "ModelHub", "zh-Hant": "ModelHub", "en": "ModelHub", "ja": "ModelHub",
        "ko": "ModelHub", "es": "ModelHub", "fr": "ModelHub", "de": "ModelHub",
        "pt-BR": "ModelHub", "ru": "ModelHub", "ar": "ModelHub",
    ],
    "兼容 API Base URL": [
        "zh-Hans": "兼容 API Base URL", "zh-Hant": "相容 API Base URL", "en": "Compatible API Base URL",
        "ja": "互換 API Base URL", "ko": "호환 API Base URL", "es": "URL base de API compatible",
        "fr": "URL de base de l’API compatible", "de": "Basis-URL der kompatiblen API", "pt-BR": "URL base da API compatível",
        "ru": "Базовый URL совместимого API", "ar": "عنوان URL الأساسي لواجهة API المتوافقة",
    ],
    "Token": [
        "zh-Hans": "Token", "zh-Hant": "Token", "en": "Token", "ja": "トークン",
        "ko": "토큰", "es": "Token", "fr": "Jeton", "de": "Token",
        "pt-BR": "Token", "ru": "Токен", "ar": "الرمز",
    ],
    "模型枢纽": [
        "zh-Hans": "模型枢纽", "zh-Hant": "模型樞紐", "en": "ModelHub",
        "ja": "ModelHub", "ko": "ModelHub", "es": "ModelHub", "fr": "ModelHub",
        "de": "ModelHub", "pt-BR": "ModelHub", "ru": "ModelHub", "ar": "ModelHub",
    ],
    "模型供应商": [
        "zh-Hans": "模型供应商", "zh-Hant": "模型供應商", "en": "Model Providers",
        "ja": "モデルプロバイダー", "ko": "모델 제공업체", "es": "Proveedores de modelos",
        "fr": "Fournisseurs de modèles", "de": "Modellanbieter", "pt-BR": "Provedores de modelos",
        "ru": "Поставщики моделей", "ar": "موفّرو النماذج",
    ],
    "模型路由": [
        "zh-Hans": "模型路由", "zh-Hant": "模型路由", "en": "Model Routes",
        "ja": "モデルルート", "ko": "모델 경로", "es": "Rutas de modelos",
        "fr": "Routes de modèles", "de": "Modellrouten", "pt-BR": "Rotas de modelos",
        "ru": "Маршруты моделей", "ar": "مسارات النماذج",
    ],
    "供应商": [
        "zh-Hans": "供应商", "zh-Hant": "供應商", "en": "Provider", "ja": "プロバイダー",
        "ko": "제공업체", "es": "Proveedor", "fr": "Fournisseur", "de": "Anbieter",
        "pt-BR": "Provedor", "ru": "Поставщик", "ar": "المزوّد",
    ],
    "供应商 / 模型": [
        "zh-Hans": "供应商 / 模型", "zh-Hant": "供應商 / 模型", "en": "Provider / Model",
        "ja": "プロバイダー / モデル", "ko": "제공업체 / 모델", "es": "Proveedor / Modelo",
        "fr": "Fournisseur / Modèle", "de": "Anbieter / Modell", "pt-BR": "Provedor / Modelo",
        "ru": "Поставщик / Модель", "ar": "المزوّد / النموذج",
    ],
    "供应商类型": [
        "zh-Hans": "供应商类型", "zh-Hant": "供應商類型", "en": "Provider Type",
        "ja": "プロバイダーの種類", "ko": "제공업체 유형", "es": "Tipo de proveedor",
        "fr": "Type de fournisseur", "de": "Anbietertyp", "pt-BR": "Tipo de provedor",
        "ru": "Тип поставщика", "ar": "نوع المزوّد",
    ],
    "用量分析": [
        "zh-Hans": "用量分析", "zh-Hant": "用量分析", "en": "Usage Analytics",
        "ja": "使用状況分析", "ko": "사용량 분석", "es": "Análisis de uso",
        "fr": "Analyse de l’utilisation", "de": "Nutzungsanalyse", "pt-BR": "Análise de uso",
        "ru": "Аналитика использования", "ar": "تحليلات الاستخدام",
    ],
    "凭证": [
        "zh-Hans": "凭证", "zh-Hant": "憑證", "en": "Credentials", "ja": "認証情報",
        "ko": "자격 증명", "es": "Credenciales", "fr": "Identifiants", "de": "Anmeldedaten",
        "pt-BR": "Credenciais", "ru": "Учётные данные", "ar": "بيانات الاعتماد",
    ],
    "韧性控制": [
        "zh-Hans": "韧性控制", "zh-Hant": "韌性控制", "en": "Resilience Controls",
        "ja": "耐障害性制御", "ko": "복원력 제어", "es": "Controles de resiliencia",
        "fr": "Contrôles de résilience", "de": "Resilienzsteuerung", "pt-BR": "Controles de resiliência",
        "ru": "Управление отказоустойчивостью", "ar": "عناصر التحكم في المرونة",
    ],
    "本机 Agent 协议": [
        "zh-Hans": "本机 Agent 协议", "zh-Hant": "本機 Agent 協議", "en": "Local Agent Protocols",
        "ja": "ローカル Agent プロトコル", "ko": "로컬 Agent 프로토콜", "es": "Protocolos locales de Agent",
        "fr": "Protocoles Agent locaux", "de": "Lokale Agent-Protokolle", "pt-BR": "Protocolos locais de Agent",
        "ru": "Локальные протоколы Agent", "ar": "بروتوكولات Agent المحلية",
    ],
    "熔断冷却：%arg 秒": [
        "zh-Hans": "熔断冷却：%arg 秒", "zh-Hant": "熔斷冷卻：%arg 秒", "en": "Circuit-breaker cooldown: %arg seconds",
        "ja": "サーキットブレーカーのクールダウン：%arg 秒", "ko": "회로 차단기 대기 시간: %arg초",
        "es": "Espera del disyuntor: %arg segundos", "fr": "Délai du coupe-circuit : %arg secondes",
        "de": "Abkühlzeit des Schutzschalters: %arg Sekunden", "pt-BR": "Espera do disjuntor: %arg segundos",
        "ru": "Пауза автоматического выключателя: %arg с", "ar": "مهلة قاطع الدائرة: %arg ثانية",
    ],
    "上下文优化": [
        "zh-Hans": "上下文优化", "zh-Hant": "上下文最佳化", "en": "Context Optimization",
        "ja": "コンテキスト最適化", "ko": "컨텍스트 최적화", "es": "Optimización del contexto",
        "fr": "Optimisation du contexte", "de": "Kontextoptimierung", "pt-BR": "Otimização de contexto",
        "ru": "Оптимизация контекста", "ar": "تحسين السياق",
    ],
    "好": [
        "zh-Hans": "好", "zh-Hant": "好", "en": "OK", "ja": "OK", "ko": "확인",
        "es": "Aceptar", "fr": "OK", "de": "OK", "pt-BR": "OK", "ru": "ОК", "ar": "موافق",
    ],
]

let reviewedEnglish: [String: String] = [
    "%arg 个目标": "%arg targets",
    "%arg 个模型 · 聊天模型在线检测；生成模型未通过原生验证时保持隔离": "%arg models · chat models are tested online; generative models stay quarantined until native verification passes",
    "%arg原生入口": "%arg native endpoint",
    "%@原生入口": "%@ native endpoint",
    "一键测试": "Test All",
    "仅监听 127.0.0.1 并校验本机 Origin；生成工具需确认可能计费，所有调用仍经过隔离、限流、预算与日志。": "Listens only on 127.0.0.1 and validates local origins. Generation tools require billable-call confirmation, and every request still passes through quarantine, rate limits, budgets, and logging.",
    "MCP 可读取本机状态、可用模型、聚合用量和你保存的任务文本，也可调用文字、图片、视频、语音、向量与重排模型；不会自动读取 Codex/Claude 的全部会话或返回密钥。": "MCP can read local status, available models, aggregate usage, and task text you saved, and can invoke text, image, video, speech, embedding, and reranking models. It does not automatically read entire Codex or Claude conversations or return secrets.",
    "优先级数值越小越先尝试；权重仅用于权重随机策略。5xx、429 或网络错误会触发故障转移。": "Lower priority values are tried first. Weights apply only to weighted-random routing. HTTP 5xx, 429, and network errors trigger failover.",
    "例如：供应商定价页 / 手工": "Example: provider pricing page / manual entry",
    "删除供应商？": "Delete provider?",
    "启用整理的最小字符数：%arg": "Minimum characters before cleanup: %arg",
    "将检查 %arg 个模型。已隔离的聊天模型也会重新请求上游，成功后自动恢复，失败则继续隔离。图像、视频、语音、转录、向量和重排模型只验证本地原生适配，不自动发起可能计费的生成。最多并发 3 个，单次超时 30 秒。": "%arg models will be checked. Quarantined chat models are probed again and restored only after success. Image, video, speech, transcription, embedding, and reranking models validate local protocol support without starting billable generation. At most 3 requests run concurrently, with a 30-second timeout each.",
    "月 Token 上限": "Monthly token limit",
    "月度费用上限（USD，留空表示不设）": "Monthly spend limit (USD; leave blank for none)",
    "本月暂无聚合用量。未知价格不会被伪算为已知费用。": "No aggregated usage this month. Models with unknown pricing are not reported as known costs.",
    "耗时": "Duration",
    "启用此供应商": "Enable this provider",
    "添加供应商": "Add provider",
    "编辑供应商与密钥": "Edit provider and key",
    "选择供应商": "Select provider",
    "选择左侧供应商后查看模型状态。": "Select a provider on the left to view model status.",
    "熔断冷却：%arg 秒": "Circuit-breaker cooldown: %arg seconds",
    "请求模型": "Requested model",
    "连续失败熔断阈值：%arg": "Circuit-breaker threshold: %arg consecutive failures",
    "端口由 ModelHub 与 ProjectDock 固定管理，仅监听本机回环地址；请保留末尾 /v1。": "ModelHub and ProjectDock manage this fixed loopback-only port. Keep /v1 at the end.",
    "模型": "Model",
    "保存": "Save",
    "停止": "Stop",
    "成功": "Success",
    "未知": "Unknown",
    "响应": "Response",
    "时间": "Time",
    "访问令牌": "Access Token",
    "路由规则": "Routing Rules",
]

let additional: [String: [String]] = [
    "· 已取得 task_id": ["· task_id received", "· task_id を取得", "· task_id 수신", "· task_id recibido", "· task_id reçu", "· task_id erhalten", "· task_id recebido", "· task_id получен", "· تم استلام task_id"],
    "[已脱敏]": ["[Redacted]", "[マスク済み]", "[마스킹됨]", "[Ocultado]", "[Masqué]", "[Geschwärzt]", "[Ocultado]", "[Скрыто]", "[منقّح]"],
    "测试前已重新拉取 %d 个目录参考项；该目录不代表可直接调用模型，未自动导入或测试。": ["Refreshed %d catalog reference items before testing. This catalog does not identify directly callable models, so nothing was imported or tested automatically.", "テスト前にカタログ参照項目を %d 件更新しました。このカタログは直接呼び出せるモデルを示すものではないため、自動インポートやテストは行っていません。", "테스트 전에 카탈로그 참고 항목 %d개를 새로 가져왔습니다. 이 카탈로그는 직접 호출 가능한 모델을 뜻하지 않으므로 자동으로 가져오거나 테스트하지 않았습니다.", "Se actualizaron %d elementos de referencia del catálogo antes de la prueba. Este catálogo no identifica modelos invocables directamente, por lo que no se importó ni probó nada automáticamente.", "%d éléments de référence du catalogue ont été actualisés avant le test. Ce catalogue n’identifie pas des modèles directement appelables ; rien n’a donc été importé ni testé automatiquement.", "Vor dem Test wurden %d Katalogreferenzen aktualisiert. Dieser Katalog weist keine direkt aufrufbaren Modelle aus; daher wurde nichts automatisch importiert oder getestet.", "Foram atualizados %d itens de referência do catálogo antes do teste. Esse catálogo não identifica modelos diretamente chamáveis; nada foi importado ou testado automaticamente.", "Перед тестированием обновлено %d справочных элементов каталога. Каталог не означает, что модели можно вызывать напрямую, поэтому автоматический импорт и тестирование не выполнялись.", "تم تحديث %d عنصرًا مرجعيًا من الدليل قبل الاختبار. لا يعني هذا الدليل أن النماذج قابلة للاستدعاء مباشرة، لذلك لم يتم استيرادها أو اختبارها تلقائيًا."],
    "测试已取消": ["Test cancelled", "テストをキャンセルしました", "테스트 취소됨", "Prueba cancelada", "Test annulé", "Test abgebrochen", "Teste cancelado", "Тест отменён", "تم إلغاء الاختبار"],
    "测试请求编码失败": ["Failed to encode the test request", "テストリクエストのエンコードに失敗しました", "테스트 요청 인코딩 실패", "No se pudo codificar la solicitud de prueba", "Échec de l’encodage de la requête de test", "Testanfrage konnte nicht codiert werden", "Falha ao codificar a solicitação de teste", "Не удалось закодировать тестовый запрос", "فشل ترميز طلب الاختبار"],
    "请求重试已达上限": ["Request retry limit reached", "リクエストの再試行上限に達しました", "요청 재시도 한도에 도달함", "Se alcanzó el límite de reintentos", "Limite de nouvelles tentatives atteinte", "Maximale Anzahl der Anfragewiederholungen erreicht", "Limite de novas tentativas atingido", "Достигнут предел повторных запросов", "تم بلوغ حد إعادة محاولة الطلب"],
    "这是可部署参考目录，不代表模型名可直接调用。已默认不勾选；只应导入你已部署并拿到调用代码的项目。": ["This is a deployable reference catalog, not a list of directly callable model IDs. Items are unselected by default; import only deployments for which you have the invocation code.", "これはデプロイ可能な参照カタログであり、直接呼び出せるモデル ID の一覧ではありません。既定では未選択です。デプロイ済みで呼び出しコードを取得した項目だけをインポートしてください。", "배포 가능한 참고 카탈로그이며 직접 호출할 수 있는 모델 ID 목록이 아닙니다. 기본적으로 선택되지 않습니다. 배포했고 호출 코드를 받은 항목만 가져오세요.", "Este es un catálogo de referencia desplegable, no una lista de identificadores de modelo invocables directamente. Los elementos están desmarcados de forma predeterminada; importa solo despliegues cuyo código de invocación tengas.", "Il s’agit d’un catalogue de référence déployable, pas d’une liste d’identifiants de modèles directement appelables. Les éléments sont décochés par défaut ; importez uniquement les déploiements dont vous possédez le code d’appel.", "Dies ist ein Referenzkatalog bereitstellbarer Modelle, keine Liste direkt aufrufbarer Modell-IDs. Einträge sind standardmäßig abgewählt; importieren Sie nur Bereitstellungen, deren Aufrufcode Ihnen vorliegt.", "Este é um catálogo de referência implantável, não uma lista de IDs de modelos diretamente chamáveis. Os itens vêm desmarcados; importe apenas implantações cujo código de chamada você possui.", "Это справочный каталог доступных для развёртывания моделей, а не список идентификаторов для прямого вызова. Элементы по умолчанию не выбраны; импортируйте только развёртывания, для которых у вас есть код вызова.", "هذا دليل مرجعي للنماذج القابلة للنشر، وليس قائمة بمعرّفات نماذج قابلة للاستدعاء مباشرة. العناصر غير محددة افتراضيًا؛ استورد فقط عمليات النشر التي لديك رمز استدعائها."],
    "零费用检测 %lld 个模型": ["Zero-cost check for %lld models", "%lld モデルを無料チェック", "%lld개 모델 무료 검사", "Comprobación sin coste de %lld modelos", "Vérification sans frais de %lld modèles", "Kostenlose Prüfung von %lld Modellen", "Verificação sem custo de %lld modelos", "Бесплатная проверка %lld моделей", "فحص %lld نموذجًا دون تكلفة"],
    "包含 %lld 个原生验证（可能计费）": ["Include %lld native verifications (may incur charges)", "%lld 件のネイティブ検証を含める（課金の可能性あり）", "%lld개 네이티브 검증 포함(요금이 발생할 수 있음)", "Incluir %lld verificaciones nativas (puede generar cargos)", "Inclure %lld validations natives (facturation possible)", "%lld native Prüfungen einschließen (möglicherweise kostenpflichtig)", "Incluir %lld verificações nativas (pode gerar cobranças)", "Включить %lld нативных проверок (возможна оплата)", "تضمين %lld عملية تحقق أصلية (قد تُفرض رسوم)"],
    "将检查 %lld 个模型。零费用检测不会创建生成任务；选择包含原生验证后，会对 %lld 个生成类模型各发送一次最小真实请求，可能逐模型计费。成功且响应包含有效任务标识后自动解封。最多并发 3 个。": ["%lld models will be checked. The zero-cost check creates no generation tasks. If native verification is included, one minimal real request is sent to each of %lld generative models and may be billed per model. A model is restored only after success with a valid task identifier. Up to 3 requests run concurrently.", "%lld モデルを確認します。無料チェックでは生成タスクを作成しません。ネイティブ検証を含めると、%lld 個の生成モデルそれぞれに最小限の実リクエストを 1 回送信し、モデルごとに課金される可能性があります。有効なタスク ID を伴う成功後にのみ隔離を解除します。同時実行は最大 3 件です。", "%lld개 모델을 검사합니다. 무료 검사는 생성 작업을 만들지 않습니다. 네이티브 검증을 포함하면 %lld개 생성 모델 각각에 최소 실제 요청을 한 번 보내며 모델별 요금이 발생할 수 있습니다. 유효한 작업 ID가 포함된 성공 응답 후에만 격리를 해제합니다. 최대 3개 요청을 동시에 실행합니다.", "Se comprobarán %lld modelos. La comprobación sin coste no crea tareas de generación. Si se incluye la verificación nativa, se envía una solicitud real mínima a cada uno de los %lld modelos generativos y puede cobrarse por modelo. Solo se restaura tras una respuesta correcta con un identificador de tarea válido. Máximo 3 solicitudes simultáneas.", "%lld modèles seront vérifiés. La vérification sans frais ne crée aucune tâche de génération. Si la validation native est incluse, une requête réelle minimale est envoyée à chacun des %lld modèles génératifs et peut être facturée par modèle. La restauration n’a lieu qu’après une réponse réussie contenant un identifiant de tâche valide. Maximum 3 requêtes simultanées.", "%lld Modelle werden geprüft. Die kostenlose Prüfung erstellt keine Generierungsaufträge. Bei nativer Prüfung wird an jedes der %lld generativen Modelle eine minimale echte Anfrage gesendet, die pro Modell kostenpflichtig sein kann. Die Freigabe erfolgt nur nach einer erfolgreichen Antwort mit gültiger Task-ID. Maximal 3 gleichzeitige Anfragen.", "%lld modelos serão verificados. A verificação sem custo não cria tarefas de geração. Ao incluir a verificação nativa, uma solicitação real mínima é enviada a cada um dos %lld modelos generativos e pode ser cobrada por modelo. A liberação ocorre somente após uma resposta bem-sucedida com identificador de tarefa válido. Até 3 solicitações simultâneas.", "Будут проверены %lld моделей. Бесплатная проверка не создаёт задачи генерации. При включении нативной проверки каждому из %lld генеративных моделей отправляется один минимальный реальный запрос, который может оплачиваться отдельно. Изоляция снимается только после успешного ответа с действительным идентификатором задачи. Одновременно выполняется не более 3 запросов.", "سيتم فحص %lld نموذجًا. لا ينشئ الفحص دون تكلفة مهام توليد. عند تضمين التحقق الأصلي، يُرسل طلب حقيقي أدنى إلى كل واحد من نماذج التوليد البالغ عددها %lld وقد تُفرض رسوم لكل نموذج. لا يُرفع العزل إلا بعد نجاح الاستجابة واحتوائها على معرّف مهمة صالح. الحد الأقصى 3 طلبات متزامنة."],
    "一键同步官方价格": ["Sync Official Prices", "公式価格を同期", "공식 가격 동기화", "Sincronizar precios oficiales", "Synchroniser les tarifs officiels", "Offizielle Preise synchronisieren", "Sincronizar preços oficiais", "Синхронизировать официальные цены", "مزامنة الأسعار الرسمية"],
    "热更新模型": ["Hot-update Models", "モデルをホット更新", "모델 핫 업데이트", "Actualizar modelos en caliente", "Actualiser les modèles à chaud", "Modelle live aktualisieren", "Atualizar modelos a quente", "Горячее обновление моделей", "تحديث النماذج فورياً"],
    "从已保存的精确模型目录增量合并，不重启服务；新增模型保持隔离，现有状态不变。": ["Incrementally merges the saved exact model catalog without restarting the service. New models stay quarantined and existing statuses remain unchanged.", "保存済みの正確なモデルカタログをサービス再起動なしで差分統合します。新しいモデルは隔離され、既存の状態は変わりません。", "저장된 정확한 모델 카탈로그를 서비스 재시작 없이 증분 병합합니다. 새 모델은 격리 상태로 유지되고 기존 상태는 변경되지 않습니다.", "Fusiona de forma incremental el catálogo exacto guardado sin reiniciar el servicio. Los modelos nuevos quedan aislados y los estados existentes no cambian.", "Fusionne progressivement le catalogue exact enregistré sans redémarrer le service. Les nouveaux modèles restent en quarantaine et les états existants ne changent pas.", "Führt den gespeicherten exakten Modellkatalog ohne Dienstneustart inkrementell zusammen. Neue Modelle bleiben in Quarantäne, bestehende Status bleiben unverändert.", "Mescla incrementalmente o catálogo exato salvo sem reiniciar o serviço. Novos modelos permanecem em quarentena e os estados existentes não mudam.", "Инкрементально объединяет сохранённый точный каталог без перезапуска службы. Новые модели остаются изолированными, текущие статусы не меняются.", "يدمج دليل النماذج الدقيق المحفوظ تدريجياً دون إعادة تشغيل الخدمة. تبقى النماذج الجديدة معزولة ولا تتغير الحالات الحالية."],
    "该供应商没有已保存或已核验的精确模型名录 URL；不会使用或补全 Base URL。": ["This provider has no saved or verified exact model catalog URL. The Base URL will not be used or completed.", "このプロバイダーには保存済みまたは確認済みの正確なモデルカタログ URL がありません。Base URL の使用や補完は行いません。", "이 공급자에는 저장되었거나 검증된 정확한 모델 카탈로그 URL이 없습니다. Base URL은 사용하거나 보완하지 않습니다.", "Este proveedor no tiene una URL exacta del catálogo guardada o verificada. No se usará ni completará la URL base.", "Ce fournisseur ne possède aucune URL exacte de catalogue enregistrée ou vérifiée. L’URL de base ne sera ni utilisée ni complétée.", "Für diesen Anbieter ist keine gespeicherte oder geprüfte exakte Modellkatalog-URL vorhanden. Die Basis-URL wird weder verwendet noch ergänzt.", "Este provedor não tem uma URL exata do catálogo salva ou verificada. A URL base não será usada nem completada.", "Для этого поставщика нет сохранённого или проверенного точного URL каталога. Базовый URL не используется и не дополняется.", "لا يتوفر لهذا المزوّد عنوان دقيق محفوظ أو متحقق منه لدليل النماذج. لن يُستخدم عنوان URL الأساسي أو يُستكمل."],
    "读取到 %lld 个目录参考项，但该目录不代表可直接调用模型，未执行热更新。": ["Read %lld catalog reference items, but this catalog does not identify directly callable models, so no hot update was applied.", "%lld 件のカタログ参照項目を取得しましたが、直接呼び出せるモデルを示すものではないためホット更新は行いませんでした。", "카탈로그 참고 항목 %lld개를 읽었지만 직접 호출 가능한 모델 목록이 아니므로 핫 업데이트를 적용하지 않았습니다.", "Se leyeron %lld elementos de referencia, pero el catálogo no identifica modelos invocables directamente, por lo que no se aplicó la actualización en caliente.", "%lld éléments de référence ont été lus, mais ce catalogue n’identifie pas des modèles directement appelables ; aucune actualisation à chaud n’a été appliquée.", "%lld Katalogreferenzen wurden gelesen. Da der Katalog keine direkt aufrufbaren Modelle ausweist, wurde keine Live-Aktualisierung durchgeführt.", "Foram lidos %lld itens de referência, mas o catálogo não identifica modelos diretamente chamáveis; nenhuma atualização a quente foi aplicada.", "Прочитано %lld справочных записей, но каталог не определяет модели для прямого вызова, поэтому горячее обновление не выполнено.", "تمت قراءة %lld عنصراً مرجعياً، لكن الدليل لا يحدد نماذج قابلة للاستدعاء مباشرة، لذلك لم يُطبّق التحديث الفوري."],
    "热更新完成：读取 %lld 个目录项，新增 %lld 个模型；新增模型保持隔离，现有模型和检测状态未修改。": ["Hot update complete: read %lld catalog items and added %lld models. New models remain quarantined; existing models and verification statuses were unchanged.", "ホット更新完了：カタログ %lld 件を読み取り、%lld モデルを追加しました。新しいモデルは隔離され、既存モデルと検証状態は変更されていません。", "핫 업데이트 완료: 카탈로그 항목 %lld개를 읽고 모델 %lld개를 추가했습니다. 새 모델은 격리 상태이며 기존 모델과 검증 상태는 변경되지 않았습니다.", "Actualización en caliente completada: se leyeron %lld elementos y se añadieron %lld modelos. Los nuevos quedan aislados; los modelos y estados existentes no cambiaron.", "Actualisation à chaud terminée : %lld éléments lus et %lld modèles ajoutés. Les nouveaux restent en quarantaine ; les modèles et états existants sont inchangés.", "Live-Aktualisierung abgeschlossen: %lld Katalogeinträge gelesen, %lld Modelle hinzugefügt. Neue Modelle bleiben in Quarantäne; bestehende Modelle und Prüfstatus wurden nicht geändert.", "Atualização a quente concluída: %lld itens lidos e %lld modelos adicionados. Novos modelos permanecem em quarentena; modelos e estados existentes não mudaram.", "Горячее обновление завершено: прочитано %lld записей, добавлено %lld моделей. Новые модели изолированы; существующие модели и статусы проверки не изменены.", "اكتمل التحديث الفوري: تمت قراءة %lld عنصراً وإضافة %lld نموذجاً. تبقى النماذج الجديدة معزولة ولم تتغير النماذج أو حالات التحقق الحالية."],
    "模型热更新失败：%@": ["Model hot update failed: %@", "モデルのホット更新に失敗しました：%@", "모델 핫 업데이트 실패: %@", "Error en la actualización en caliente del modelo: %@", "Échec de l’actualisation à chaud des modèles : %@", "Live-Aktualisierung der Modelle fehlgeschlagen: %@", "Falha na atualização a quente dos modelos: %@", "Ошибка горячего обновления моделей: %@", "فشل التحديث الفوري للنماذج: %@"],
    "单次价格": ["Per-request price", "リクエスト単価", "요청당 가격", "Precio por solicitud", "Tarif par requête", "Preis pro Anfrage", "Preço por solicitação", "Цена за запрос", "السعر لكل طلب"],
    "每次调用价格": ["Per-call price", "呼び出し単価", "호출당 가격", "Precio por llamada", "Tarif par appel", "Preis pro Aufruf", "Preço por chamada", "Цена за вызов", "السعر لكل استدعاء"],
    "输入单价": ["Input unit price", "入力単価", "입력 단가", "Precio unitario de entrada", "Prix unitaire d’entrée", "Eingabe-Einheitspreis", "Preço unitário de entrada", "Цена единицы ввода", "سعر وحدة الإدخال"],
    "输出单价": ["Output unit price", "出力単価", "출력 단가", "Precio unitario de salida", "Prix unitaire de sortie", "Ausgabe-Einheitspreis", "Preço unitário de saída", "Цена единицы вывода", "سعر وحدة الإخراج"],
    "模型_id": ["model_id", "model_id", "model_id", "model_id", "model_id", "model_id", "model_id", "model_id", "model_id"],
    "模型标识": ["Model identifier", "モデル識別子", "모델 식별자", "Identificador del modelo", "Identifiant du modèle", "Modellkennung", "Identificador do modelo", "Идентификатор модели", "معرّف النموذج"],
    "价格": ["Prices", "価格", "가격", "Precios", "Tarifs", "Preise", "Preços", "Цены", "الأسعار"],
    "供应商模型目录没有返回带明确单位的机器可读价格；现有费用未被修改。": ["The provider catalog returned no machine-readable prices with explicit units; existing costs were not changed.", "プロバイダーカタログに単位が明記された機械可読価格がないため、既存の費用は変更されませんでした。", "공급자 카탈로그에 단위가 명시된 기계 판독 가격이 없어 기존 비용을 변경하지 않았습니다.", "El catálogo del proveedor no devolvió precios legibles por máquina con unidades explícitas; no se modificaron los costes existentes.", "Le catalogue du fournisseur n’a renvoyé aucun tarif lisible par machine avec unité explicite ; les coûts existants n’ont pas été modifiés.", "Der Anbieterkatalog lieferte keine maschinenlesbaren Preise mit eindeutiger Einheit; vorhandene Kosten wurden nicht geändert.", "O catálogo do provedor não retornou preços legíveis por máquina com unidades explícitas; os custos existentes não foram alterados.", "Каталог поставщика не вернул машиночитаемых цен с явными единицами; существующие расходы не изменены.", "لم يُرجع دليل المزوّد أسعارًا قابلة للقراءة آليًا بوحدات واضحة؛ لم تتغير التكاليف الحالية."],
    "供应商目录 / 手工": ["Provider catalog / Manual", "プロバイダーカタログ / 手動", "공급자 카탈로그 / 수동", "Catálogo del proveedor / Manual", "Catalogue fournisseur / Manuel", "Anbieterkatalog / Manuell", "Catálogo do provedor / Manual", "Каталог поставщика / Вручную", "دليل المزوّد / يدوي"],
    "供应商目录或手动配置": ["Provider catalog or manual configuration", "プロバイダーカタログまたは手動設定", "공급자 카탈로그 또는 수동 구성", "Catálogo del proveedor o configuración manual", "Catalogue fournisseur ou configuration manuelle", "Anbieterkatalog oder manuelle Konfiguration", "Catálogo do provedor ou configuração manual", "Каталог поставщика или ручная настройка", "دليل المزوّد أو إعداد يدوي"],
    "供应商返回了价格，但没有与当前模型名称匹配；现有费用未被修改。": ["The provider returned prices, but none matched the current model names; existing costs were not changed.", "プロバイダーは価格を返しましたが、現在のモデル名と一致しなかったため、既存の費用は変更されませんでした。", "공급자가 가격을 반환했지만 현재 모델 이름과 일치하지 않아 기존 비용을 변경하지 않았습니다.", "El proveedor devolvió precios, pero ninguno coincidió con los nombres actuales; no se modificaron los costes existentes.", "Le fournisseur a renvoyé des tarifs, mais aucun ne correspond aux noms actuels ; les coûts existants n’ont pas été modifiés.", "Der Anbieter lieferte Preise, aber keiner passte zu den aktuellen Modellnamen; vorhandene Kosten wurden nicht geändert.", "O provedor retornou preços, mas nenhum correspondeu aos nomes atuais; os custos existentes não foram alterados.", "Поставщик вернул цены, но они не совпали с текущими именами моделей; существующие расходы не изменены.", "أرجع المزوّد أسعارًا، لكنها لم تطابق أسماء النماذج الحالية؛ لم تتغير التكاليف الحالية."],
    "为保持界面流畅，当前显示前 %lld 个匹配模型；输入更精确的名称可配置其余模型。": ["To keep the interface responsive, only the first %lld matching models are shown. Enter a more specific name to configure the rest.", "画面の応答性を保つため、最初の %lld 件のみ表示しています。残りを設定するには、より具体的な名前を入力してください。", "인터페이스 반응성을 위해 일치하는 모델 중 처음 %lld개만 표시합니다. 나머지를 구성하려면 더 구체적인 이름을 입력하세요.", "Para mantener una interfaz fluida solo se muestran los primeros %lld modelos coincidentes. Introduce un nombre más específico para configurar el resto.", "Pour préserver la fluidité, seuls les %lld premiers modèles correspondants sont affichés. Saisissez un nom plus précis pour configurer les autres.", "Für eine flüssige Oberfläche werden nur die ersten %lld passenden Modelle angezeigt. Geben Sie einen genaueren Namen ein, um weitere zu konfigurieren.", "Para manter a interface responsiva, apenas os primeiros %lld modelos correspondentes são exibidos. Informe um nome mais específico para configurar os demais.", "Для сохранения отзывчивости показаны только первые %lld совпавших моделей. Укажите более точное имя, чтобы настроить остальные.", "للحفاظ على سلاسة الواجهة، تُعرض أول %lld من النماذج المطابقة فقط. أدخل اسمًا أدق لضبط البقية."],
    "单次调用价格": ["Per-request price", "1 リクエスト当たりの価格", "요청당 가격", "Precio por solicitud", "Tarif par requête", "Preis pro Anfrage", "Preço por solicitação", "Цена за запрос", "السعر لكل طلب"],
    "固定 $/次": ["Fixed $/request", "固定 $/リクエスト", "고정 $/요청", "$ fijo/solicitud", "$ fixe/requête", "Fest $/Anfrage", "$ fixo/solicitação", "Фикс. $/запрос", "ثابت $/طلب"],
    "手动配置": ["Manual configuration", "手動設定", "수동 구성", "Configuración manual", "Configuration manuelle", "Manuelle Konfiguration", "Configuração manual", "Ручная настройка", "إعداد يدوي"],
    "未配置费用": ["No cost configured", "費用未設定", "비용 미구성", "Sin coste configurado", "Coût non configuré", "Keine Kosten konfiguriert", "Custo não configurado", "Стоимость не настроена", "لم تُضبط التكلفة"],
    "正在从供应商模型目录读取价格…": ["Reading prices from the provider catalog…", "プロバイダーカタログから価格を読み取っています…", "공급자 카탈로그에서 가격을 읽는 중…", "Leyendo precios del catálogo del proveedor…", "Lecture des tarifs depuis le catalogue fournisseur…", "Preise werden aus dem Anbieterkatalog gelesen…", "Lendo preços do catálogo do provedor…", "Чтение цен из каталога поставщика…", "جارٍ قراءة الأسعار من دليل المزوّد…"],
    "清除费用": ["Clear costs", "費用を消去", "비용 지우기", "Borrar costes", "Effacer les coûts", "Kosten löschen", "Limpar custos", "Очистить стоимость", "مسح التكاليف"],
    "精确端点": ["Exact endpoints", "正確なエンドポイント", "정확한 엔드포인트", "Endpoints exactos", "Points de terminaison exacts", "Exakte Endpunkte", "Endpoints exatos", "Точные адреса", "نقاط النهاية الدقيقة"],
    "美元/次": ["USD/request", "USD/リクエスト", "USD/요청", "USD/solicitud", "USD/requête", "USD/Anfrage", "USD/solicitação", "USD/запрос", "دولار/طلب"],
    "美元/百万 Token": ["USD/million tokens", "USD/100 万トークン", "USD/백만 토큰", "USD/millón de tokens", "USD/million de jetons", "USD/Million Token", "USD/milhão de tokens", "USD/миллион токенов", "دولار/مليون رمز"],
    "请先填写供应商自身提供的精确模型名录 URL。": ["Enter the exact model catalog URL provided by the provider first.", "プロバイダー自身が提供する正確なモデルカタログ URL を入力してください。", "공급자가 직접 제공한 정확한 모델 카탈로그 URL을 먼저 입력하세요.", "Introduce primero la URL exacta del catálogo proporcionada por el proveedor.", "Saisissez d’abord l’URL exacte du catalogue fournie par le fournisseur.", "Geben Sie zuerst die exakte, vom Anbieter bereitgestellte Modellkatalog-URL ein.", "Informe primeiro a URL exata do catálogo fornecida pelo provedor.", "Сначала укажите точный URL каталога, предоставленный поставщиком.", "أدخل أولًا عنوان دليل النماذج الدقيق الذي يقدمه المزوّد."],
    "请选择一个 CSV 文件。导入前会先显示模型预览。": ["Select a CSV file. A model preview appears before import.", "CSV ファイルを選択してください。インポート前にモデルのプレビューが表示されます。", "CSV 파일을 선택하세요. 가져오기 전에 모델 미리보기가 표시됩니다.", "Selecciona un archivo CSV. Se mostrará una vista previa antes de importarlo.", "Sélectionnez un fichier CSV. Un aperçu des modèles s’affichera avant l’import.", "Wählen Sie eine CSV-Datei. Vor dem Import wird eine Modellvorschau angezeigt.", "Selecione um arquivo CSV. Uma prévia dos modelos será exibida antes da importação.", "Выберите CSV-файл. Перед импортом будет показан предварительный список моделей.", "اختر ملف CSV. ستظهر معاينة للنماذج قبل الاستيراد."],
    "费用管理": ["Cost Management", "費用管理", "비용 관리", "Gestión de costes", "Gestion des coûts", "Kostenverwaltung", "Gerenciamento de custos", "Управление расходами", "إدارة التكاليف"],
    "自动价格只读取供应商自身模型目录明确返回的机器可读金额与单位；不会抓取第三方价格、不会猜价。所有模型都可以在下方手动配置。": ["Automatic pricing reads only machine-readable amounts and units explicitly returned by the provider catalog. It never scrapes third-party prices or guesses. Every model can also be configured manually below.", "自動価格取得は、プロバイダーカタログが明示的に返す機械可読の金額と単位のみを読み取ります。第三者価格の取得や推測は行いません。すべてのモデルを下で手動設定できます。", "자동 가격은 공급자 카탈로그가 명시적으로 반환한 기계 판독 금액과 단위만 읽습니다. 제3자 가격을 수집하거나 추측하지 않습니다. 모든 모델은 아래에서 수동으로 구성할 수 있습니다.", "La obtención automática solo lee importes y unidades legibles por máquina devueltos explícitamente por el catálogo del proveedor. No extrae precios de terceros ni los adivina. Todos los modelos también pueden configurarse manualmente.", "La tarification automatique ne lit que les montants et unités lisibles par machine explicitement renvoyés par le catalogue fournisseur. Elle n’extrait aucun tarif tiers et ne devine rien. Chaque modèle peut aussi être configuré manuellement.", "Die automatische Preisübernahme liest nur maschinenlesbare Beträge und Einheiten, die der Anbieterkatalog ausdrücklich liefert. Drittanbieterpreise werden weder ausgelesen noch geschätzt. Jedes Modell kann unten manuell konfiguriert werden.", "A precificação automática lê apenas valores e unidades legíveis por máquina retornados explicitamente pelo catálogo do provedor. Não coleta preços de terceiros nem faz estimativas. Todos os modelos também podem ser configurados manualmente.", "Автоматическое получение цен читает только машиночитаемые суммы и единицы, явно возвращённые каталогом поставщика. Цены третьих лиц не собираются и не угадываются. Любую модель можно настроить вручную ниже.", "لا يقرأ التسعير التلقائي إلا المبالغ والوحدات القابلة للقراءة آليًا التي يعيدها دليل المزوّد صراحةً. ولا يجلب أسعار أطراف ثالثة أو يخمّنها. ويمكن ضبط كل نموذج يدويًا أدناه."],
    "CSV 支持 UTF-8、UTF-16 与 Excel 分隔符声明。必填列：model（也支持 model_id、模型名称）；可选列：endpoint、各协议端点、input_price、output_price、request_price、price_source。Token 价格单位为美元/百万 Token，request_price 为美元/次。": ["CSV supports UTF-8, UTF-16, and Excel separator declarations. Required: model (also model_id or 模型名称). Optional: endpoint, protocol endpoints, input_price, output_price, request_price, and price_source. Token prices use USD per million tokens; request_price uses USD per request.", "CSV は UTF-8、UTF-16、Excel の区切り文字宣言に対応します。必須列：model（model_id、模型名称も可）。任意列：endpoint、各プロトコルのエンドポイント、input_price、output_price、request_price、price_source。トークン価格は 100 万トークン当たり USD、request_price は 1 リクエスト当たり USD です。", "CSV는 UTF-8, UTF-16 및 Excel 구분자 선언을 지원합니다. 필수 열: model(model_id, 模型名称 지원). 선택 열: endpoint, 프로토콜별 엔드포인트, input_price, output_price, request_price, price_source. 토큰 가격은 백만 토큰당 USD, request_price는 요청당 USD입니다.", "CSV admite UTF-8, UTF-16 y declaraciones de separador de Excel. Obligatoria: model (también model_id o 模型名称). Opcionales: endpoint, endpoints por protocolo, input_price, output_price, request_price y price_source. Los precios de tokens son USD por millón; request_price es USD por solicitud.", "Le CSV prend en charge UTF-8, UTF-16 et les déclarations de séparateur Excel. Colonne requise : model (aussi model_id ou 模型名称). Facultatives : endpoint, points de terminaison par protocole, input_price, output_price, request_price et price_source. Les tarifs de jetons sont en USD par million ; request_price en USD par requête.", "CSV unterstützt UTF-8, UTF-16 und Excel-Trennzeichendeklarationen. Pflicht: model (auch model_id oder 模型名称). Optional: endpoint, Protokoll-Endpunkte, input_price, output_price, request_price und price_source. Tokenpreise sind USD pro Million Token; request_price ist USD pro Anfrage.", "CSV aceita UTF-8, UTF-16 e declarações de separador do Excel. Obrigatória: model (também model_id ou 模型名称). Opcionais: endpoint, endpoints por protocolo, input_price, output_price, request_price e price_source. Preços de tokens usam USD por milhão; request_price usa USD por solicitação.", "CSV поддерживает UTF-8, UTF-16 и объявления разделителя Excel. Обязательный столбец: model (также model_id или 模型名称). Необязательные: endpoint, адреса протоколов, input_price, output_price, request_price и price_source. Цены токенов — USD за миллион, request_price — USD за запрос.", "يدعم CSV ترميزَي UTF-8 وUTF-16 وتصريح فاصل Excel. العمود المطلوب: model (وكذلك model_id أو 模型名称). الاختيارية: endpoint ونقاط نهاية البروتوكولات وinput_price وoutput_price وrequest_price وprice_source. أسعار الرموز بالدولار لكل مليون، وrequest_price بالدولار لكل طلب."],
    "默认每天本机时间 00:00 更新。只读取供应商自身已配置或已核验的官方模型目录，不修改 Base URL、不合并新模型、不调用生成接口；仅当目录明确提供 Token 或单次调用价格及单位时更新，其他供应商保留手动价格。": ["By default, updates run daily at 00:00 local time. Only provider-owned configured or verified official catalogs are read. The Base URL is not changed, new models are not imported, and generation APIs are not called. Prices update only when token or per-request amounts and units are explicit; otherwise manual prices remain.", "既定ではローカル時刻 00:00 に毎日更新します。プロバイダー自身の設定済みまたは確認済み公式カタログのみを読み取り、Base URL の変更、新モデルの統合、生成 API の呼び出しは行いません。トークンまたはリクエスト単価と単位が明示される場合のみ更新し、それ以外は手動価格を保持します。", "기본값은 현지 시간 매일 00:00입니다. 공급자가 소유한 구성 또는 검증된 공식 카탈로그만 읽고 Base URL 변경, 새 모델 병합, 생성 API 호출은 하지 않습니다. 토큰 또는 요청당 금액과 단위가 명확할 때만 업데이트하며 나머지는 수동 가격을 유지합니다.", "De forma predeterminada se actualiza cada día a las 00:00, hora local. Solo se leen catálogos configurados o verificados propiedad del proveedor; no se modifica la URL base, no se importan modelos ni se llaman API de generación. Solo se actualiza cuando el importe y la unidad por token o solicitud son explícitos; en los demás casos se conserva el precio manual.", "Par défaut, la mise à jour a lieu chaque jour à 00:00, heure locale. Seuls les catalogues configurés ou officiels vérifiés appartenant au fournisseur sont lus ; l’URL de base n’est pas modifiée, aucun modèle n’est importé et aucune API de génération n’est appelée. Les tarifs ne changent que si les montants et unités par jeton ou requête sont explicites ; sinon les valeurs manuelles restent.", "Standardmäßig erfolgt die Aktualisierung täglich um 00:00 Uhr Ortszeit. Gelesen werden nur konfigurierte oder geprüfte offizielle Kataloge des Anbieters; Basis-URL, Modellliste und Generierungs-APIs bleiben unberührt. Aktualisiert wird nur bei eindeutigen Token- oder Anfragebeträgen samt Einheit; sonst bleiben manuelle Preise erhalten.", "Por padrão, a atualização ocorre diariamente às 00:00 no horário local. Apenas catálogos do próprio provedor, configurados ou oficiais verificados, são lidos; a URL base não muda, novos modelos não são importados e APIs de geração não são chamadas. Só há atualização quando valores e unidades por token ou solicitação são explícitos; caso contrário, os preços manuais permanecem.", "По умолчанию обновление выполняется ежедневно в 00:00 по местному времени. Читаются только настроенные или проверенные официальные каталоги самого поставщика; базовый URL не меняется, модели не импортируются и API генерации не вызываются. Обновление происходит только при явных суммах и единицах за токены или запрос; иначе сохраняются ручные цены.", "يُجرى التحديث افتراضيًا يوميًا عند 00:00 بالتوقيت المحلي. لا تُقرأ إلا أدلة المزوّد نفسه المهيأة أو الرسمية المتحقق منها، ولا يتغير عنوان URL الأساسي ولا تُدمج نماذج جديدة ولا تُستدعى واجهات التوليد. لا تُحدّث الأسعار إلا عند وجود مبالغ ووحدات واضحة للرموز أو لكل طلب؛ وإلا تبقى الأسعار اليدوية."],
    "CSV 文件超过安全上限（%lld MiB）": ["The CSV file exceeds the safety limit (%lld MiB)", "CSV ファイルが安全上限（%lld MiB）を超えています", "CSV 파일이 안전 한도(%lld MiB)를 초과합니다", "El archivo CSV supera el límite de seguridad (%lld MiB)", "Le fichier CSV dépasse la limite de sécurité (%lld Mio)", "Die CSV-Datei überschreitet das Sicherheitslimit (%lld MiB)", "O arquivo CSV excede o limite de segurança (%lld MiB)", "CSV-файл превышает безопасный предел (%lld МиБ)", "يتجاوز ملف CSV حد الأمان (%lld MiB)"],
    "CSV 模型数量超过安全上限（%lld）": ["The number of CSV models exceeds the safety limit (%lld)", "CSV のモデル数が安全上限（%lld）を超えています", "CSV 모델 수가 안전 한도(%lld)를 초과합니다", "El número de modelos del CSV supera el límite de seguridad (%lld)", "Le nombre de modèles CSV dépasse la limite de sécurité (%lld)", "Die Anzahl der CSV-Modelle überschreitet das Sicherheitslimit (%lld)", "O número de modelos CSV excede o limite de segurança (%lld)", "Число моделей в CSV превышает безопасный предел (%lld)", "يتجاوز عدد نماذج CSV حد الأمان (%lld)"],
    "CSV 第 %lld 行的 %@ 必须是大于或等于 0 的数字": ["CSV row %lld: %@ must be a number greater than or equal to 0", "CSV の %lld 行目：%@ は 0 以上の数値である必要があります", "CSV %lld행: %@은(는) 0 이상의 숫자여야 합니다", "Fila %lld del CSV: %@ debe ser un número mayor o igual que 0", "Ligne %lld du CSV : %@ doit être un nombre supérieur ou égal à 0", "CSV-Zeile %lld: %@ muss eine Zahl größer oder gleich 0 sein", "Linha %lld do CSV: %@ deve ser um número maior ou igual a 0", "Строка CSV %lld: %@ должно быть числом не меньше 0", "صف CSV رقم %lld: يجب أن تكون %@ رقمًا أكبر من أو يساوي 0"],
    "CSV 第 %lld 行的 %@ 必须是无凭证的完整 HTTP(S) URL": ["CSV row %lld: %@ must be a complete HTTP(S) URL without credentials", "CSV の %lld 行目：%@ は認証情報を含まない完全な HTTP(S) URL である必要があります", "CSV %lld행: %@은(는) 자격 증명이 없는 완전한 HTTP(S) URL이어야 합니다", "Fila %lld del CSV: %@ debe ser una URL HTTP(S) completa y sin credenciales", "Ligne %lld du CSV : %@ doit être une URL HTTP(S) complète sans identifiants", "CSV-Zeile %lld: %@ muss eine vollständige HTTP(S)-URL ohne Anmeldedaten sein", "Linha %lld do CSV: %@ deve ser uma URL HTTP(S) completa sem credenciais", "Строка CSV %lld: %@ должен быть полным HTTP(S)-URL без учётных данных", "صف CSV رقم %lld: يجب أن تكون %@ عنوان HTTP(S) كاملاً دون بيانات اعتماد"],
    "CSV 第 %lld 行的引号格式不完整": ["CSV row %lld has an incomplete quoted field", "CSV の %lld 行目の引用符形式が不完全です", "CSV %lld행의 따옴표 형식이 완전하지 않습니다", "La fila %lld del CSV tiene un campo entrecomillado incompleto", "La ligne %lld du CSV contient un champ entre guillemets incomplet", "CSV-Zeile %lld enthält ein unvollständig zitiertes Feld", "A linha %lld do CSV tem um campo entre aspas incompleto", "В строке CSV %lld не закрыто поле в кавычках", "يحتوي صف CSV رقم %lld على حقل مقتبس غير مكتمل"],
    "CSV 第 %lld 行的模型名称为空、过长或包含控制字符": ["CSV row %lld has an empty or overly long model name, or contains control characters", "CSV の %lld 行目のモデル名が空、長すぎる、または制御文字を含んでいます", "CSV %lld행의 모델 이름이 비어 있거나 너무 길거나 제어 문자를 포함합니다", "La fila %lld del CSV tiene un nombre de modelo vacío, demasiado largo o con caracteres de control", "La ligne %lld du CSV contient un nom de modèle vide, trop long ou avec des caractères de contrôle", "CSV-Zeile %lld enthält einen leeren oder zu langen Modellnamen oder Steuerzeichen", "A linha %lld do CSV tem um nome de modelo vazio, longo demais ou com caracteres de controle", "В строке CSV %lld имя модели пустое, слишком длинное или содержит управляющие символы", "اسم النموذج في صف CSV رقم %lld فارغ أو طويل جدًا أو يحتوي على محارف تحكم"],
    "%@，隔离原因：%@": ["%@, quarantine reason: %@", "%@、隔離理由：%@", "%@, 격리 사유: %@", "%@, motivo del aislamiento: %@", "%@, motif de la mise en quarantaine : %@", "%@, Quarantänegrund: %@", "%@, motivo da quarentena: %@", "%@, причина изоляции: %@", "%@، سبب العزل: %@"],
    "API Key 无效或已过期": ["The API key is invalid or expired", "API Key が無効か期限切れです", "API Key가 유효하지 않거나 만료되었습니다", "La clave API no es válida o ha caducado", "La clé API est invalide ou expirée", "Der API-Schlüssel ist ungültig oder abgelaufen", "A chave de API é inválida ou expirou", "Ключ API недействителен или просрочен", "مفتاح API غير صالح أو منتهي الصلاحية"],
    "CSV 只接受 UTF-8 编码的 .csv 文件。必填列：model（也支持“模型名称”）；可选列：endpoint、各协议端点、input_price、output_price、price_source。价格单位为美元/百万 Token。": ["CSV import accepts only UTF-8 .csv files. Required: model (or 模型名称). Optional: endpoint, protocol-specific endpoints, input_price, output_price, and price_source. Prices are USD per million tokens.", "CSV は UTF-8 の .csv ファイルのみ対応します。必須列：model（または「模型名称」）。任意列：endpoint、各プロトコルのエンドポイント、input_price、output_price、price_source。価格単位は 100 万トークン当たりの米ドルです。", "CSV 가져오기는 UTF-8 .csv 파일만 지원합니다. 필수 열: model(또는 模型名称). 선택 열: endpoint, 프로토콜별 엔드포인트, input_price, output_price, price_source. 가격 단위는 백만 토큰당 USD입니다.", "La importación CSV solo acepta archivos .csv UTF-8. Columna obligatoria: model (o 模型名称). Opcionales: endpoint, endpoints por protocolo, input_price, output_price y price_source. Los precios son USD por millón de tokens.", "L’import CSV accepte uniquement les fichiers .csv UTF-8. Colonne requise : model (ou 模型名称). Colonnes facultatives : endpoint, points de terminaison par protocole, input_price, output_price et price_source. Les tarifs sont en USD par million de jetons.", "Der CSV-Import akzeptiert nur UTF-8-kodierte .csv-Dateien. Pflichtspalte: model (oder 模型名称). Optional: endpoint, protokollspezifische Endpunkte, input_price, output_price und price_source. Preise sind USD pro Million Token.", "A importação CSV aceita apenas arquivos .csv em UTF-8. Coluna obrigatória: model (ou 模型名称). Opcionais: endpoint, endpoints por protocolo, input_price, output_price e price_source. Os preços são em USD por milhão de tokens.", "Импортируются только CSV-файлы в UTF-8. Обязательный столбец: model (или 模型名称). Необязательные: endpoint, адреса протоколов, input_price, output_price и price_source. Цены указываются в USD за миллион токенов.", "يقبل استيراد CSV ملفات ‎.csv بترميز UTF-8 فقط. العمود المطلوب: model (أو 模型名称). الأعمدة الاختيارية: endpoint ونقاط نهاية البروتوكولات وinput_price وoutput_price وprice_source. الأسعار بالدولار لكل مليون رمز."],
    "CSV 导入只会在确认后合并所选模型、价格和精确端点；不会修改 Base URL，也不会把模型标记为可用。": ["CSV import merges selected models, prices, and exact endpoints only after confirmation. It does not change the Base URL or mark models as available.", "CSV インポートは確認後に選択したモデル、価格、正確なエンドポイントだけを統合します。Base URL は変更せず、モデルを利用可能にも設定しません。", "CSV 가져오기는 확인 후 선택한 모델, 가격, 정확한 엔드포인트만 병합합니다. Base URL을 변경하거나 모델을 사용 가능으로 표시하지 않습니다.", "La importación CSV solo combina los modelos, precios y endpoints exactos seleccionados tras la confirmación. No cambia la URL base ni marca modelos como disponibles.", "L’import CSV fusionne uniquement les modèles, tarifs et points de terminaison exacts sélectionnés après confirmation. Il ne modifie pas l’URL de base et ne marque pas les modèles comme disponibles.", "Der CSV-Import führt ausgewählte Modelle, Preise und exakte Endpunkte erst nach Bestätigung zusammen. Er ändert weder die Basis-URL noch markiert er Modelle als verfügbar.", "A importação CSV só mescla os modelos, preços e endpoints exatos selecionados após confirmação. Ela não altera a URL base nem marca modelos como disponíveis.", "CSV-импорт объединяет выбранные модели, цены и точные адреса только после подтверждения. Базовый URL не меняется, модели не отмечаются доступными.", "لا يدمج استيراد CSV النماذج والأسعار ونقاط النهاية الدقيقة المحددة إلا بعد التأكيد، ولا يغيّر عنوان URL الأساسي ولا يضع علامة متاح على النماذج."],
    "CSV 文件中没有可导入的模型": ["The CSV file contains no importable models", "CSV ファイルにインポート可能なモデルがありません", "CSV 파일에 가져올 수 있는 모델이 없습니다", "El archivo CSV no contiene modelos importables", "Le fichier CSV ne contient aucun modèle importable", "Die CSV-Datei enthält keine importierbaren Modelle", "O arquivo CSV não contém modelos importáveis", "В CSV-файле нет моделей для импорта", "لا يحتوي ملف CSV على نماذج قابلة للاستيراد"],
    "CSV 文件必须使用 UTF-8 编码": ["The CSV file must use UTF-8 encoding", "CSV ファイルは UTF-8 である必要があります", "CSV 파일은 UTF-8 인코딩이어야 합니다", "El archivo CSV debe usar codificación UTF-8", "Le fichier CSV doit être encodé en UTF-8", "Die CSV-Datei muss UTF-8-kodiert sein", "O arquivo CSV deve usar codificação UTF-8", "CSV-файл должен быть в кодировке UTF-8", "يجب أن يستخدم ملف CSV ترميز UTF-8"],
    "CSV 文件必须使用 UTF-8 或 UTF-16 编码": ["The CSV file must use UTF-8 or UTF-16 encoding", "CSV ファイルは UTF-8 または UTF-16 である必要があります", "CSV 파일은 UTF-8 또는 UTF-16 인코딩이어야 합니다", "El archivo CSV debe usar codificación UTF-8 o UTF-16", "Le fichier CSV doit être encodé en UTF-8 ou UTF-16", "Die CSV-Datei muss UTF-8- oder UTF-16-kodiert sein", "O arquivo CSV deve usar codificação UTF-8 ou UTF-16", "CSV-файл должен использовать UTF-8 или UTF-16", "يجب أن يستخدم ملف CSV ترميز UTF-8 أو UTF-16"],
    "CSV 文件缺少表头": ["The CSV file is missing a header row", "CSV ファイルにヘッダー行がありません", "CSV 파일에 헤더 행이 없습니다", "Falta la fila de encabezado en el archivo CSV", "La ligne d’en-tête manque dans le fichier CSV", "Der CSV-Datei fehlt eine Kopfzeile", "O arquivo CSV não tem linha de cabeçalho", "В CSV-файле отсутствует строка заголовков", "يفتقد ملف CSV إلى صف العناوين"],
    "CSV 表头必须包含 model 或 模型名称 列": ["The CSV header must include a model or 模型名称 column", "CSV ヘッダーには model または 模型名称 列が必要です", "CSV 헤더에는 model 또는 模型名称 열이 있어야 합니다", "El encabezado CSV debe incluir una columna model o 模型名称", "L’en-tête CSV doit contenir une colonne model ou 模型名称", "Die CSV-Kopfzeile muss eine Spalte model oder 模型名称 enthalten", "O cabeçalho CSV deve incluir uma coluna model ou 模型名称", "Заголовок CSV должен содержать столбец model или 模型名称", "يجب أن يتضمن عنوان CSV عمود model أو 模型名称"],
    "responses端点": ["Responses endpoint", "Responses エンドポイント", "Responses 엔드포인트", "Endpoint de Responses", "Point de terminaison Responses", "Responses-Endpunkt", "Endpoint de Responses", "Адрес Responses", "نقطة نهاية Responses"],
    "上游未找到该模型，或精确调用端点不匹配": ["The upstream did not find this model, or the exact request endpoint does not match", "上流でモデルが見つからないか、正確な呼び出し先が一致していません", "업스트림에서 모델을 찾지 못했거나 정확한 호출 엔드포인트가 일치하지 않습니다", "El servicio de origen no encontró el modelo o el endpoint exacto no coincide", "Le service en amont n’a pas trouvé ce modèle ou le point de terminaison exact ne correspond pas", "Der Upstream hat das Modell nicht gefunden oder der exakte Aufrufendpunkt stimmt nicht", "O serviço upstream não encontrou o modelo ou o endpoint exato não corresponde", "Поставщик не нашёл модель либо точный адрес вызова не соответствует", "لم يجد المزوّد النموذج أو أن نقطة نهاية الاستدعاء الدقيقة غير مطابقة"],
    "上游请求超时，请检查网络或稍后重试": ["The upstream request timed out. Check the network or try again later", "上流リクエストがタイムアウトしました。ネットワークを確認するか後でもう一度お試しください", "업스트림 요청 시간이 초과되었습니다. 네트워크를 확인하거나 나중에 다시 시도하세요", "La solicitud al servicio de origen agotó el tiempo. Comprueba la red o inténtalo más tarde", "La requête en amont a expiré. Vérifiez le réseau ou réessayez plus tard", "Die Upstream-Anfrage hat das Zeitlimit überschritten. Netzwerk prüfen oder später erneut versuchen", "A solicitação upstream expirou. Verifique a rede ou tente novamente mais tarde", "Превышено время ожидания поставщика. Проверьте сеть или повторите позже", "انتهت مهلة طلب المزوّد. تحقق من الشبكة أو أعد المحاولة لاحقًا"],
    "供应商服务暂时异常": ["The provider service is temporarily unavailable", "プロバイダーのサービスが一時的に利用できません", "공급자 서비스에 일시적인 문제가 있습니다", "El servicio del proveedor no está disponible temporalmente", "Le service du fournisseur est temporairement indisponible", "Der Anbieterdienst ist vorübergehend nicht verfügbar", "O serviço do provedor está temporariamente indisponível", "Сервис поставщика временно недоступен", "خدمة المزوّد غير متاحة مؤقتًا"],
    "最近一次验证失败，请查看技术详情并重新测试": ["The latest verification failed. Review the technical details and test again", "前回の検証に失敗しました。技術詳細を確認して再テストしてください", "최근 검증에 실패했습니다. 기술 세부 정보를 확인하고 다시 테스트하세요", "La última verificación falló. Revisa los detalles técnicos y vuelve a probar", "La dernière vérification a échoué. Consultez les détails techniques et relancez le test", "Die letzte Prüfung ist fehlgeschlagen. Technische Details prüfen und erneut testen", "A última verificação falhou. Revise os detalhes técnicos e teste novamente", "Последняя проверка не пройдена. Изучите технические сведения и повторите тест", "فشل آخر تحقق. راجع التفاصيل التقنية وأعد الاختبار"],
    "原生生成协议尚未完成真实验证": ["The native generation protocol has not completed real verification", "ネイティブ生成プロトコルはまだ実際の検証を完了していません", "네이티브 생성 프로토콜이 실제 검증을 완료하지 않았습니다", "El protocolo nativo de generación aún no ha completado una verificación real", "Le protocole de génération natif n’a pas encore passé de vérification réelle", "Das native Generierungsprotokoll wurde noch nicht real geprüft", "O protocolo nativo de geração ainda não concluiu a verificação real", "Нативный протокол генерации ещё не прошёл реальную проверку", "لم يُكمل بروتوكول التوليد الأصلي التحقق الحقيقي بعد"],
    "只允许导入 .csv 格式的文件。": ["Only .csv files can be imported.", ".csv 形式のファイルのみインポートできます。", ".csv 형식의 파일만 가져올 수 있습니다.", "Solo se pueden importar archivos .csv.", "Seuls les fichiers .csv peuvent être importés.", "Es können nur .csv-Dateien importiert werden.", "Somente arquivos .csv podem ser importados.", "Можно импортировать только файлы .csv.", "لا يمكن استيراد سوى ملفات ‎.csv."],
    "向量端点": ["Embedding endpoint", "埋め込みエンドポイント", "임베딩 엔드포인트", "Endpoint de embeddings", "Point de terminaison d’embeddings", "Embedding-Endpunkt", "Endpoint de embeddings", "Адрес эмбеддингов", "نقطة نهاية التضمينات"],
    "图片端点": ["Image endpoint", "画像エンドポイント", "이미지 엔드포인트", "Endpoint de imágenes", "Point de terminaison d’images", "Bild-Endpunkt", "Endpoint de imagens", "Адрес изображений", "نقطة نهاية الصور"],
    "导入 CSV": ["Import CSV", "CSV をインポート", "CSV 가져오기", "Importar CSV", "Importer un CSV", "CSV importieren", "Importar CSV", "Импортировать CSV", "استيراد CSV"],
    "尚未完成真实可用性验证": ["Real availability verification has not been completed", "実際の可用性検証が完了していません", "실제 가용성 검증이 완료되지 않았습니다", "No se ha completado la verificación real de disponibilidad", "La vérification réelle de disponibilité n’est pas terminée", "Die reale Verfügbarkeitsprüfung ist noch nicht abgeschlossen", "A verificação real de disponibilidade não foi concluída", "Реальная проверка доступности ещё не завершена", "لم يكتمل التحقق الحقيقي من التوفر"],
    "当前凭证无权访问此模型": ["The current credential is not authorized to access this model", "現在の認証情報にはこのモデルへのアクセス権がありません", "현재 자격 증명에는 이 모델에 대한 접근 권한이 없습니다", "Las credenciales actuales no tienen permiso para acceder a este modelo", "Les identifiants actuels ne permettent pas d’accéder à ce modèle", "Die aktuellen Anmeldedaten sind für dieses Modell nicht berechtigt", "A credencial atual não tem permissão para acessar este modelo", "Текущие учётные данные не дают доступа к этой модели", "بيانات الاعتماد الحالية غير مخولة للوصول إلى هذا النموذج"],
    "当前版本尚未适配此模型协议": ["This app version does not yet support this model protocol", "このバージョンはまだこのモデルのプロトコルに対応していません", "현재 버전은 이 모델 프로토콜을 아직 지원하지 않습니다", "Esta versión aún no admite el protocolo de este modelo", "Cette version ne prend pas encore en charge le protocole de ce modèle", "Diese Version unterstützt das Modellprotokoll noch nicht", "Esta versão ainda não é compatível com o protocolo deste modelo", "Эта версия ещё не поддерживает протокол модели", "هذا الإصدار لا يدعم بروتوكول النموذج بعد"],
    "视频任务端点": ["Video task endpoint", "動画タスクエンドポイント", "비디오 작업 엔드포인트", "Endpoint de tareas de vídeo", "Point de terminaison des tâches vidéo", "Videoaufgaben-Endpunkt", "Endpoint de tarefas de vídeo", "Адрес задач видео", "نقطة نهاية مهام الفيديو"],
    "视频端点": ["Video endpoint", "動画エンドポイント", "비디오 엔드포인트", "Endpoint de vídeo", "Point de terminaison vidéo", "Video-Endpunkt", "Endpoint de vídeo", "Адрес видео", "نقطة نهاية الفيديو"],
    "缺少 API Key，未向供应商发起请求": ["The API key is missing; no request was sent to the provider", "API Key がないため、プロバイダーへのリクエストは送信されませんでした", "API Key가 없어 공급자에게 요청을 보내지 않았습니다", "Falta la clave API; no se envió ninguna solicitud al proveedor", "La clé API manque ; aucune requête n’a été envoyée au fournisseur", "Der API-Schlüssel fehlt; es wurde keine Anfrage an den Anbieter gesendet", "A chave de API está ausente; nenhuma solicitação foi enviada ao provedor", "Ключ API отсутствует; запрос поставщику не отправлялся", "مفتاح API مفقود؛ لم يُرسل أي طلب إلى المزوّد"],
    "网络连接失败，未能完成上游验证": ["The network connection failed, so upstream verification could not complete", "ネットワーク接続に失敗し、上流の検証を完了できませんでした", "네트워크 연결 실패로 업스트림 검증을 완료하지 못했습니다", "Falló la conexión de red y no se pudo completar la verificación del servicio de origen", "La connexion réseau a échoué ; la vérification en amont n’a pas pu aboutir", "Die Netzwerkverbindung ist fehlgeschlagen; die Upstream-Prüfung konnte nicht abgeschlossen werden", "A conexão de rede falhou e a verificação upstream não foi concluída", "Сбой сетевого соединения; проверка поставщика не завершена", "فشل اتصال الشبكة وتعذر إكمال تحقق المزوّد"],
    "聊天端点": ["Chat endpoint", "チャットエンドポイント", "채팅 엔드포인트", "Endpoint de chat", "Point de terminaison de chat", "Chat-Endpunkt", "Endpoint de chat", "Адрес чата", "نقطة نهاية الدردشة"],
    "语音端点": ["Speech endpoint", "音声エンドポイント", "음성 엔드포인트", "Endpoint de voz", "Point de terminaison vocal", "Sprach-Endpunkt", "Endpoint de voz", "Адрес речи", "نقطة نهاية الكلام"],
    "请求受限或账户配额不足": ["The request was rate-limited or the account quota is insufficient", "リクエストが制限されたか、アカウントの割り当てが不足しています", "요청이 제한되었거나 계정 할당량이 부족합니다", "La solicitud está limitada o la cuota de la cuenta es insuficiente", "La requête est limitée ou le quota du compte est insuffisant", "Die Anfrage wurde begrenzt oder das Kontingent reicht nicht aus", "A solicitação foi limitada ou a cota da conta é insuficiente", "Запрос ограничен либо квота аккаунта исчерпана", "تم تقييد الطلب أو أن حصة الحساب غير كافية"],
    "请求格式、参数或模型能力不匹配": ["The request format, parameters, or model capability do not match", "リクエスト形式、パラメータ、またはモデル機能が一致しません", "요청 형식, 매개변수 또는 모델 기능이 일치하지 않습니다", "El formato, los parámetros o la capacidad del modelo no coinciden", "Le format de requête, les paramètres ou la capacité du modèle ne correspondent pas", "Anfrageformat, Parameter oder Modellfähigkeit stimmen nicht überein", "O formato, os parâmetros ou a capacidade do modelo não correspondem", "Формат, параметры или возможности модели не соответствуют запросу", "تنسيق الطلب أو المعلمات أو قدرة النموذج غير متطابقة"],
    "转录端点": ["Transcription endpoint", "文字起こしエンドポイント", "전사 엔드포인트", "Endpoint de transcripción", "Point de terminaison de transcription", "Transkriptions-Endpunkt", "Endpoint de transcrição", "Адрес транскрипции", "نقطة نهاية النسخ"],
    "输入价格": ["Input price", "入力価格", "입력 가격", "Precio de entrada", "Tarif d’entrée", "Eingabepreis", "Preço de entrada", "Цена ввода", "سعر الإدخال"],
    "输出价格": ["Output price", "出力価格", "출력 가격", "Precio de salida", "Tarif de sortie", "Ausgabepreis", "Preço de saída", "Цена вывода", "سعر الإخراج"],
    "重排端点": ["Reranking endpoint", "再ランキングエンドポイント", "재순위화 엔드포인트", "Endpoint de reranking", "Point de terminaison de reclassement", "Reranking-Endpunkt", "Endpoint de reclassificação", "Адрес переранжирования", "نقطة نهاية إعادة الترتيب"],
    "隔离原因：%@": ["Quarantine reason: %@", "隔離理由：%@", "격리 사유: %@", "Motivo del aislamiento: %@", "Motif de la mise en quarantaine : %@", "Quarantänegrund: %@", "Motivo da quarentena: %@", "Причина изоляции: %@", "سبب العزل: %@"],
    "隔离原因：%@\n技术详情：%@": ["Quarantine reason: %@\nTechnical details: %@", "隔離理由：%@\n技術詳細：%@", "격리 사유: %@\n기술 세부 정보: %@", "Motivo del aislamiento: %@\nDetalles técnicos: %@", "Motif de la mise en quarantaine : %@\nDétails techniques : %@", "Quarantänegrund: %@\nTechnische Details: %@", "Motivo da quarentena: %@\nDetalhes técnicos: %@", "Причина изоляции: %@\nТехнические сведения: %@", "سبب العزل: %@\nالتفاصيل التقنية: %@"],
    "；目录同时提供可自动同步的 Token 价格。": ["; the catalog also provides token prices that can be synchronized automatically.", "；カタログには自動同期できるトークン価格も含まれます。", "; 카탈로그는 자동 동기화 가능한 토큰 가격도 제공합니다.", "; el catálogo también proporciona precios de tokens que se pueden sincronizar automáticamente.", " ; le catalogue fournit aussi des tarifs de jetons synchronisables automatiquement.", "; der Katalog enthält auch automatisch synchronisierbare Tokenpreise.", "; o catálogo também fornece preços de tokens que podem ser sincronizados automaticamente.", "; каталог также содержит цены токенов для автоматической синхронизации.", "؛ يوفر الدليل أيضًا أسعار الرموز القابلة للمزامنة تلقائيًا."],
    "；该目录未公开可直接同步的 Token 价格。": ["; this catalog does not publish token prices that can be synchronized directly.", "；このカタログは直接同期できるトークン価格を公開していません。", "; 이 카탈로그는 직접 동기화할 수 있는 토큰 가격을 공개하지 않습니다.", "; este catálogo no publica precios de tokens que puedan sincronizarse directamente.", " ; ce catalogue ne publie pas de tarifs de jetons directement synchronisables.", "; dieser Katalog veröffentlicht keine direkt synchronisierbaren Tokenpreise.", "; este catálogo não publica preços de tokens que possam ser sincronizados diretamente.", "; этот каталог не публикует цены токенов для прямой синхронизации.", "؛ لا ينشر هذا الدليل أسعار رموز قابلة للمزامنة مباشرة."],
    "%02d 分": ["%02d min", "%02d 分", "%02d분", "%02d min", "%02d min", "%02d Min.", "%02d min", "%02d мин", "%02d دقيقة"],
    "%02d 时": ["%02d h", "%02d 時", "%02d시", "%02d h", "%02d h", "%02d Uhr", "%02d h", "%02d ч", "%02d ساعة"],
    "Base URL 始终按原样保存；切换供应商类型不会自动填写、补版本或追加路径。": ["The Base URL is always saved exactly as entered. Changing provider type will not fill it, add a version, or append a path.", "Base URL は入力どおりに保存されます。プロバイダー種類を変更しても、自動入力、バージョン補完、パス追加は行いません。", "Base URL은 입력한 그대로 저장됩니다. 공급자 유형을 바꿔도 자동 입력, 버전 보완 또는 경로 추가를 하지 않습니다.", "La URL base siempre se guarda tal como se introdujo. Cambiar el tipo de proveedor no la rellenará ni añadirá una versión o ruta.", "L’URL de base est toujours enregistrée telle quelle. Changer de fournisseur ne la complète pas et n’ajoute ni version ni chemin.", "Die Basis-URL wird unverändert gespeichert. Ein Anbieterwechsel ergänzt weder Version noch Pfad.", "A URL base é sempre salva exatamente como informada. Alterar o tipo de provedor não a preencherá nem adicionará versão ou caminho.", "Базовый URL всегда сохраняется без изменений. Смена типа поставщика не добавляет версию или путь.", "يُحفظ عنوان URL الأساسي كما أُدخل تمامًا، ولا يؤدي تغيير نوع المزوّد إلى إكماله أو إضافة إصدار أو مسار."],
    "ModelHub Agent 令牌未配置。请在启动该 ACP 进程时设置 MODELHUB_AGENT_TOKEN。": ["The ModelHub Agent token is not configured. Set MODELHUB_AGENT_TOKEN when starting this ACP process.", "ModelHub Agent トークンが設定されていません。この ACP プロセスの起動時に MODELHUB_AGENT_TOKEN を設定してください。", "ModelHub Agent 토큰이 구성되지 않았습니다. 이 ACP 프로세스를 시작할 때 MODELHUB_AGENT_TOKEN을 설정하세요.", "El token de ModelHub Agent no está configurado. Define MODELHUB_AGENT_TOKEN al iniciar este proceso ACP.", "Le jeton ModelHub Agent n’est pas configuré. Définissez MODELHUB_AGENT_TOKEN au démarrage de ce processus ACP.", "Das ModelHub-Agent-Token ist nicht konfiguriert. Setzen Sie MODELHUB_AGENT_TOKEN beim Start dieses ACP-Prozesses.", "O token do ModelHub Agent não está configurado. Defina MODELHUB_AGENT_TOKEN ao iniciar este processo ACP.", "Токен ModelHub Agent не настроен. Задайте MODELHUB_AGENT_TOKEN при запуске процесса ACP.", "رمز ModelHub Agent غير مهيأ. عيّن MODELHUB_AGENT_TOKEN عند تشغيل عملية ACP هذه."],
    "ModelHub 本机只读管理": ["ModelHub Local Read-Only Management", "ModelHub ローカル読み取り専用管理", "ModelHub 로컬 읽기 전용 관리", "Administración local de solo lectura de ModelHub", "Gestion locale en lecture seule de ModelHub", "Lokale schreibgeschützte ModelHub-Verwaltung", "Gerenciamento local somente leitura do ModelHub", "Локальное управление ModelHub только для чтения", "إدارة ModelHub المحلية للقراءة فقط"],
    "分钟": ["Minute", "分", "분", "Minuto", "Minute", "Minute", "Minuto", "Минута", "دقيقة"],
    "填入已核验官方模型目录": ["Fill Verified Official Model Catalog", "確認済みの公式モデルカタログを入力", "검증된 공식 모델 카탈로그 입력", "Rellenar catálogo oficial verificado", "Renseigner le catalogue officiel vérifié", "Geprüften offiziellen Modellkatalog eintragen", "Preencher catálogo oficial verificado", "Заполнить проверенный официальный каталог", "إدخال دليل النماذج الرسمي المتحقق منه"],
    "失败详情：": ["Failure details:", "失敗の詳細：", "실패 세부 정보:", "Detalles del fallo:", "Détails de l’échec :", "Fehlerdetails:", "Detalhes da falha:", "Сведения об ошибке:", "تفاصيل الفشل:"],
    "定时": ["Scheduled", "定時", "예약", "Programado", "Planifié", "Zeitgesteuert", "Agendado", "По расписанию", "مجدول"],
    "必须填写供应商明确提供的完整名录地址；不会使用 Base URL，也不会自动补全 /v1/models 等路径。凭证通过请求头发送，拉取结果需预览确认后才会合并。": ["Enter the complete catalog URL explicitly provided by the vendor. The Base URL is never used and paths such as /v1/models are never appended. Credentials are sent in headers, and fetched results are merged only after preview and confirmation.", "ベンダーが明示した完全なカタログ URL を入力してください。Base URL は使用せず、/v1/models などのパスも追加しません。認証情報はヘッダーで送信され、取得結果はプレビュー確認後にのみ統合されます。", "공급자가 명시한 전체 카탈로그 URL을 입력하세요. Base URL은 사용하지 않고 /v1/models 같은 경로도 추가하지 않습니다. 자격 증명은 헤더로 보내며 결과는 미리보기 확인 후에만 병합됩니다.", "Introduce la URL completa del catálogo indicada por el proveedor. Nunca se usa la URL base ni se añaden rutas como /v1/models. Las credenciales se envían en cabeceras y los resultados solo se fusionan tras revisarlos y confirmarlos.", "Saisissez l’URL complète du catalogue fournie par le fournisseur. L’URL de base n’est jamais utilisée et aucun chemin tel que /v1/models n’est ajouté. Les identifiants sont envoyés dans les en-têtes et les résultats ne sont fusionnés qu’après aperçu et confirmation.", "Geben Sie die vollständige, vom Anbieter angegebene Katalog-URL ein. Die Basis-URL wird nie verwendet und Pfade wie /v1/models werden nicht angehängt. Anmeldedaten werden in Headern gesendet; Ergebnisse werden erst nach Vorschau und Bestätigung zusammengeführt.", "Informe a URL completa do catálogo fornecida pelo provedor. A URL base nunca é usada e caminhos como /v1/models não são adicionados. As credenciais seguem nos cabeçalhos e os resultados só são mesclados após prévia e confirmação.", "Укажите полный URL каталога от поставщика. Базовый URL не используется, пути вроде /v1/models не добавляются. Учётные данные передаются в заголовках, а результаты объединяются только после просмотра и подтверждения.", "أدخل عنوان دليل النماذج الكامل الذي يحدده المزوّد. لا يُستخدم عنوان URL الأساسي ولا تُضاف مسارات مثل ‎/v1/models. تُرسل بيانات الاعتماد في الترويسات ولا تُدمج النتائج إلا بعد المعاينة والتأكيد."],
    "手动": ["Manual", "手動", "수동", "Manual", "Manuel", "Manuell", "Manual", "Вручную", "يدوي"],
    "无法读取 ModelHub 本机状态（认证失败或服务未启动）。": ["Unable to read ModelHub local status (authentication failed or service is not running).", "ModelHub のローカル状態を取得できません（認証失敗またはサービス未起動）。", "ModelHub 로컬 상태를 읽을 수 없습니다(인증 실패 또는 서비스 미실행).", "No se puede leer el estado local de ModelHub (falló la autenticación o el servicio no está activo).", "Impossible de lire l’état local de ModelHub (échec d’authentification ou service arrêté).", "Lokaler ModelHub-Status kann nicht gelesen werden (Authentifizierung fehlgeschlagen oder Dienst läuft nicht).", "Não foi possível ler o estado local do ModelHub (falha de autenticação ou serviço parado).", "Не удалось прочитать локальное состояние ModelHub: ошибка аутентификации или служба не запущена.", "تعذرت قراءة حالة ModelHub المحلية (فشلت المصادقة أو الخدمة غير مشغلة)."],
    "无法连接 ModelHub 本机服务。": ["Unable to connect to the ModelHub local service.", "ModelHub のローカルサービスに接続できません。", "ModelHub 로컬 서비스에 연결할 수 없습니다.", "No se puede conectar al servicio local de ModelHub.", "Impossible de se connecter au service local ModelHub.", "Verbindung zum lokalen ModelHub-Dienst nicht möglich.", "Não foi possível conectar ao serviço local do ModelHub.", "Не удалось подключиться к локальной службе ModelHub.", "تعذر الاتصال بخدمة ModelHub المحلية."],
    "本机 Ollama 已安装模型": ["Models installed in local Ollama", "ローカル Ollama にインストール済みのモデル", "로컬 Ollama에 설치된 모델", "Modelos instalados en Ollama local", "Modèles installés dans Ollama local", "In lokalem Ollama installierte Modelle", "Modelos instalados no Ollama local", "Модели, установленные в локальном Ollama", "النماذج المثبتة في Ollama المحلي"],
    "本机时间": ["Local Time", "ローカル時刻", "현지 시간", "Hora local", "Heure locale", "Ortszeit", "Hora local", "Местное время", "الوقت المحلي"],
    "模型价格自动更新": ["Automatic Model Price Updates", "モデル価格の自動更新", "모델 가격 자동 업데이트", "Actualización automática de precios de modelos", "Mise à jour automatique des tarifs des modèles", "Automatische Modellpreisaktualisierung", "Atualização automática de preços dos modelos", "Автоматическое обновление цен моделей", "التحديث التلقائي لأسعار النماذج"],
    "正在逐个检查已启用供应商…": ["Checking enabled providers one by one…", "有効なプロバイダーを順番に確認しています…", "활성화된 공급자를 하나씩 확인하는 중…", "Comprobando uno a uno los proveedores activados…", "Vérification séquentielle des fournisseurs activés…", "Aktivierte Anbieter werden nacheinander geprüft…", "Verificando os provedores ativados um a um…", "Последовательная проверка включённых поставщиков…", "جارٍ فحص المزوّدين المفعّلين واحدًا تلو الآخر…"],
    "每天自动读取模型价格": ["Read Model Prices Automatically Every Day", "モデル価格を毎日自動取得", "매일 모델 가격 자동 조회", "Leer automáticamente los precios cada día", "Lire automatiquement les tarifs chaque jour", "Modellpreise täglich automatisch abrufen", "Ler preços dos modelos automaticamente todos os dias", "Ежедневно автоматически получать цены моделей", "قراءة أسعار النماذج تلقائيًا كل يوم"],
    "百炼北京地域可部署的基础模型；不代表全部按量付费或语音模型": ["Base models deployable in the Bailian Beijing region; this does not represent all pay-as-you-go or speech models", "百煉の北京リージョンでデプロイ可能な基盤モデル。すべての従量課金・音声モデルを表すものではありません", "Bailian 베이징 리전에 배포 가능한 기본 모델이며 모든 종량제 또는 음성 모델을 의미하지 않습니다", "Modelos base desplegables en la región de Pekín de Bailian; no representan todos los modelos de pago por uso o de voz", "Modèles de base déployables dans la région Pékin de Bailian ; cela ne couvre pas tous les modèles à l’usage ou vocaux", "In der Bailian-Region Peking bereitstellbare Basismodelle; nicht alle nutzungsbasierten oder Sprachmodelle", "Modelos base implantáveis na região de Pequim do Bailian; não representam todos os modelos sob demanda ou de voz", "Базовые модели для развёртывания в пекинском регионе Bailian; это не все модели с оплатой по использованию или речевые модели", "النماذج الأساسية القابلة للنشر في منطقة بكين لخدمة Bailian؛ ولا تمثل جميع نماذج الدفع حسب الاستخدام أو النماذج الصوتية"],
    "立即更新模型价格": ["Update Model Prices Now", "モデル価格を今すぐ更新", "지금 모델 가격 업데이트", "Actualizar precios ahora", "Mettre à jour les tarifs maintenant", "Modellpreise jetzt aktualisieren", "Atualizar preços agora", "Обновить цены моделей сейчас", "تحديث أسعار النماذج الآن"],
    "精确模型名录 URL（不会使用 Base URL）": ["Exact Model Catalog URL (Base URL Is Not Used)", "正確なモデルカタログ URL（Base URL は使用しません）", "정확한 모델 카탈로그 URL(Base URL 사용 안 함)", "URL exacta del catálogo de modelos (no se usa la URL base)", "URL exacte du catalogue des modèles (l’URL de base n’est pas utilisée)", "Exakte Modellkatalog-URL (Basis-URL wird nicht verwendet)", "URL exata do catálogo de modelos (a URL base não é usada)", "Точный URL каталога моделей (базовый URL не используется)", "عنوان URL الدقيق لدليل النماذج (لا يُستخدم عنوان URL الأساسي)"],
    "自动补更新": ["Automatic Catch-Up", "自動補完更新", "자동 보충 업데이트", "Actualización automática pendiente", "Rattrapage automatique", "Automatisches Nachholen", "Atualização automática compensatória", "Автоматическое наверстывающее обновление", "تحديث استدراكي تلقائي"],
    "该供应商暂无已核验的公开模型目录地址，请从供应商官方文档复制完整 URL；ModelHub 不会猜测路径。": ["No verified public model catalog URL is available for this provider. Copy the complete URL from its official documentation; ModelHub will not guess a path.", "このプロバイダーには確認済みの公開モデルカタログ URL がありません。公式ドキュメントから完全な URL をコピーしてください。ModelHub はパスを推測しません。", "이 공급자는 검증된 공개 모델 카탈로그 URL이 없습니다. 공식 문서에서 전체 URL을 복사하세요. ModelHub는 경로를 추측하지 않습니다.", "No hay una URL pública verificada del catálogo para este proveedor. Copia la URL completa de su documentación oficial; ModelHub no adivinará la ruta.", "Aucune URL publique vérifiée de catalogue n’est disponible pour ce fournisseur. Copiez l’URL complète depuis sa documentation officielle ; ModelHub ne devine pas le chemin.", "Für diesen Anbieter ist keine geprüfte öffentliche Modellkatalog-URL verfügbar. Kopieren Sie die vollständige URL aus der offiziellen Dokumentation; ModelHub errät keinen Pfad.", "Não há URL pública verificada do catálogo para este provedor. Copie a URL completa da documentação oficial; o ModelHub não tentará adivinhar o caminho.", "Для этого поставщика нет проверенного публичного URL каталога. Скопируйте полный URL из официальной документации; ModelHub не угадывает путь.", "لا يتوفر عنوان عام متحقق منه لدليل هذا المزوّد. انسخ العنوان الكامل من وثائقه الرسمية؛ لن يخمّن ModelHub المسار."],
    "请先填写精确的模型名录 URL。": ["Enter the exact model catalog URL first.", "最初に正確なモデルカタログ URL を入力してください。", "먼저 정확한 모델 카탈로그 URL을 입력하세요.", "Introduce primero la URL exacta del catálogo de modelos.", "Saisissez d’abord l’URL exacte du catalogue des modèles.", "Geben Sie zuerst die exakte Modellkatalog-URL ein.", "Informe primeiro a URL exata do catálogo de modelos.", "Сначала укажите точный URL каталога моделей.", "أدخل أولًا عنوان URL الدقيق لدليل النماذج."],
    "请填写精确的模型名录 URL；模型推理 Base URL 不会被当作名录地址": ["Enter the exact model catalog URL; the inference Base URL is never treated as a catalog address", "正確なモデルカタログ URL を入力してください。推論用 Base URL はカタログアドレスとして使用されません", "정확한 모델 카탈로그 URL을 입력하세요. 추론 Base URL은 카탈로그 주소로 사용되지 않습니다", "Introduce la URL exacta del catálogo; la URL base de inferencia nunca se usa como dirección del catálogo", "Saisissez l’URL exacte du catalogue ; l’URL de base d’inférence n’est jamais utilisée comme adresse du catalogue", "Geben Sie die exakte Modellkatalog-URL ein; die Inferenz-Basis-URL wird nie als Katalogadresse verwendet", "Informe a URL exata do catálogo; a URL base de inferência nunca é usada como endereço do catálogo", "Укажите точный URL каталога; базовый URL вывода никогда не используется как адрес каталога", "أدخل عنوان URL الدقيق للدليل؛ لن يُستخدم عنوان URL الأساسي للاستدلال كعنوان للدليل"],
    "默认每天本机时间 00:00 更新。只读取已配置或已核验的官方模型目录，不修改 Base URL、不合并新模型、不调用生成接口；仅当目录明确提供 Token 单价时更新，其他供应商保留手动价格。": ["By default, updates run daily at 00:00 local time. Only configured or verified official catalogs are read. The Base URL is not changed, new models are not imported, and generation APIs are not called. Prices update only when the catalog explicitly supplies token rates; manual prices remain for other providers.", "既定ではローカル時刻 00:00 に毎日更新します。設定済みまたは確認済みの公式カタログのみを読み取り、Base URL の変更、新モデルの統合、生成 API の呼び出しは行いません。カタログがトークン単価を明示する場合のみ更新し、その他は手動価格を保持します。", "기본값은 현지 시간 매일 00:00입니다. 구성되었거나 검증된 공식 카탈로그만 읽고 Base URL 변경, 새 모델 병합, 생성 API 호출은 하지 않습니다. 카탈로그가 토큰 단가를 명시한 경우에만 업데이트하며 나머지는 수동 가격을 유지합니다.", "De forma predeterminada se actualiza cada día a las 00:00, hora local. Solo se leen catálogos configurados u oficiales verificados; no se modifica la URL base, no se importan modelos nuevos ni se llaman API de generación. Solo se actualizan precios cuando el catálogo indica tarifas por token; los demás conservan el precio manual.", "Par défaut, la mise à jour a lieu chaque jour à 00:00, heure locale. Seuls les catalogues configurés ou officiels vérifiés sont lus ; l’URL de base n’est pas modifiée, aucun nouveau modèle n’est importé et aucune API de génération n’est appelée. Les tarifs ne sont mis à jour que si le catalogue fournit explicitement un prix par jeton ; les autres restent manuels.", "Standardmäßig erfolgt die Aktualisierung täglich um 00:00 Uhr Ortszeit. Nur konfigurierte oder geprüfte offizielle Kataloge werden gelesen; Basis-URL, Modellliste und Generierungs-APIs bleiben unberührt. Preise werden nur bei ausdrücklich angegebenen Tokenpreisen aktualisiert, sonst bleiben manuelle Werte erhalten.", "Por padrão, a atualização ocorre diariamente às 00:00 no horário local. Apenas catálogos configurados ou oficiais verificados são lidos; a URL base não é alterada, novos modelos não são importados e APIs de geração não são chamadas. Os preços só mudam quando o catálogo informa claramente valores por token; os demais mantêm preços manuais.", "По умолчанию обновление выполняется ежедневно в 00:00 по местному времени. Читаются только настроенные или проверенные официальные каталоги; базовый URL не меняется, новые модели не импортируются и API генерации не вызываются. Цены обновляются только при явно указанных тарифах токенов; для остальных сохраняются ручные цены.", "يُجرى التحديث افتراضيًا يوميًا عند 00:00 بالتوقيت المحلي. لا تُقرأ إلا الأدلة المهيأة أو الرسمية المتحقق منها، ولا يتغير عنوان URL الأساسي ولا تُدمج نماذج جديدة ولا تُستدعى واجهات التوليد. لا تُحدَّث الأسعار إلا إذا قدّم الدليل سعر الرمز صراحةً، وتبقى الأسعار اليدوية لبقية المزوّدين."],
]

func providerAvailability(_ name: String) -> [String] {
    ["\(name) models available to this account", "\(name) アカウントで利用可能なモデル", "\(name) 계정에서 사용 가능한 모델", "Modelos de \(name) disponibles para esta cuenta", "Modèles \(name) disponibles pour ce compte", "Für dieses Konto verfügbare \(name)-Modelle", "Modelos \(name) disponíveis para esta conta", "Модели \(name), доступные этой учётной записи", "نماذج \(name) المتاحة لهذا الحساب"]
}

func providerPricing(_ name: String) -> [String] {
    ["\(name) models and public token prices", "\(name) のモデルと公開トークン価格", "\(name) 모델 및 공개 토큰 가격", "Modelos de \(name) y precios públicos de tokens", "Modèles \(name) et tarifs publics des jetons", "\(name)-Modelle und öffentliche Tokenpreise", "Modelos \(name) e preços públicos de tokens", "Модели \(name) и публичные цены токенов", "نماذج \(name) وأسعار الرموز المعلنة"]
}

let providerStrings: [String: [String]] = [
    "Anthropic 账户可用模型": providerAvailability("Anthropic"),
    "Cohere 账户可用模型": providerAvailability("Cohere"),
    "DeepSeek API 可用模型": providerAvailability("DeepSeek API"),
    "Fireworks 账户可用模型": providerAvailability("Fireworks"),
    "Gemini API 可用模型": providerAvailability("Gemini API"),
    "Groq 账户可用模型": providerAvailability("Groq"),
    "Mistral 账户可用模型": providerAvailability("Mistral"),
    "Perplexity 账户可用模型": providerAvailability("Perplexity"),
    "SiliconFlow 账户可用模型": providerAvailability("SiliconFlow"),
    "百度千帆账户可用模型": providerAvailability("Baidu Qianfan"),
    "OpenRouter 模型及公开 Token 价格": providerPricing("OpenRouter"),
    "Together AI 模型及公开 Token 价格": providerPricing("Together AI"),
    "xAI 可用模型及其公开 Token 价格": providerPricing("xAI"),
]

func replace(_ key: String, language: String, value: String) {
    guard var entry = strings[key] as? [String: Any] else { return }
    var localizations = entry["localizations"] as? [String: Any] ?? [:]
    localizations[language] = ["stringUnit": ["state": "translated", "value": value]]
    entry["localizations"] = localizations
    strings[key] = entry
}

for (key, localizations) in reviewed {
    for (language, value) in localizations {
        replace(key, language: language, value: value)
    }
}
for (key, value) in reviewedEnglish {
    replace(key, language: "en", value: value)
}
for (key, values) in additional.merging(providerStrings, uniquingKeysWith: { current, _ in current }) {
    guard values.count == 9 else { continue }
    for (language, value) in zip(["en", "ja", "ko", "es", "fr", "de", "pt-BR", "ru", "ar"], values) {
        replace(key, language: language, value: value)
    }
    replace(key, language: "zh-Hans", value: key)
    let traditional = NSMutableString(string: key)
    CFStringTransform(traditional, nil, "Hans-Hant" as CFString, false)
    replace(key, language: "zh-Hant", value: traditional as String)
}

let reviewURL = catalogURL
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .appendingPathComponent("scripts/localization_manual_review.json")
if
    let reviewData = try? Data(contentsOf: reviewURL),
    let reviewRoot = try? JSONSerialization.jsonObject(with: reviewData) as? [String: Any],
    let languages = reviewRoot["languages"] as? [String],
    let reviewedStrings = reviewRoot["strings"] as? [String: Any]
{
    for (key, rawValues) in reviewedStrings {
        guard let values = rawValues as? [String], values.count == languages.count else {
            fputs("Invalid manual review entry: \(key)\n", stderr)
            exit(3)
        }
        for (language, value) in zip(languages, values) {
            replace(key, language: language, value: value)
        }
        replace(key, language: "zh-Hans", value: key)
        let traditional = NSMutableString(string: key)
        CFStringTransform(traditional, nil, "Hans-Hant" as CFString, false)
        replace(key, language: "zh-Hant", value: traditional as String)
    }
}

root["strings"] = strings
let output = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
try output.write(to: catalogURL, options: .atomic)
print("Reviewed \(reviewed.count) multilingual terms and \(reviewedEnglish.count) English strings.")
